# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [10]:
a1 = pd.Series(np.random.randint(1, 5, size=100))
a2 = pd.Series(np.random.randint(1, 4, size=100))
a3 = pd.Series(np.random.randint(10000, 30000, size=100))
print(a1, a2, a3)

0     1
1     3
2     1
3     4
4     3
     ..
95    2
96    3
97    1
98    2
99    3
Length: 100, dtype: int32 0     1
1     3
2     2
3     1
4     3
     ..
95    2
96    3
97    2
98    2
99    1
Length: 100, dtype: int32 0     16769
1     21146
2     15716
3     26447
4     27473
      ...
95    15518
96    22968
97    10370
98    15175
99    20767
Length: 100, dtype: int32

### Step 3. Let's create a DataFrame by joinning the Series by column

In [12]:
hm = pd.concat([a1, a2, a3], axis=1)
hm

    0  1      2
0   1  1  16769
1   3  3  21146
2   1  2  15716
3   4  1  26447
4   3  3  27473
.. .. ..    ...
95  2  2  15518
96  3  3  22968
97  1  2  10370
98  2  2  15175
99  3  1  20767

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [14]:
hm.rename(columns= {0: 'bedrs', 1: 'bathrs', 2: 'price_sqr_meter'}, inplace=True)
hm

    bedrs  bathrs  price_sqr_meter
0       1       1            16769
1       3       3            21146
2       1       2            15716
3       4       1            26447
4       3       3            27473
..    ...     ...              ...
95      2       2            15518
96      3       3            22968
97      1       2            10370
98      2       2            15175
99      3       1            20767

[100 rows x 3 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [16]:
bc = pd.Series(pd.concat([a1, a2, a3]))
bc = bc.to_frame()
bc

        0
0       1
1       3
2       1
3       4
4       3
..    ...
95  15518
96  22968
97  10370
98  15175
99  20767

[300 rows x 1 columns]

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [17]:
# no, the indexs are kept but reality it had 300 rows of data
len(bc)

300

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [20]:
bc.reset_index(inplace=True)
bc

     level_0  index      0
0          0      0      1
1          1      1      3
2          2      2      1
3          3      3      4
4          4      4      3
..       ...    ...    ...
295      295     95  15518
296      296     96  22968
297      297     97  10370
298      298     98  15175
299      299     99  20767

[300 rows x 3 columns]